default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
        exclude: .vscode/.*.json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        exclude: (helpers|utils|conftest).py
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      # Run the Ruff linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
      # Run the Ruff formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
      - id: commitizen
      # - id: commitizen-branch
      #   stages: [push]
  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.1"
    hooks:
      - id: poetry-check
        files: poetry.lock,pyproject.toml
      - id: poetry-lock
        args: [--check]
        files: poetry.lock,pyproject.toml
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
        # regex matching poetry.lock and pyproject.toml files
        files: poetry.lock|pyproject.toml
